import { Contact, Sequence, Campaign, AIInsight } from './types';

export const contacts: Contact[] = [
  {
    id: 'c1',
    name: 'Sarah Mitchell',
    email: 'sarah.mitchell@growthco.io',
    company: 'GrowthCo',
    phone: '+1 (415) 555-0101',
    source: 'referral',
    stage: 'sales_qualified',
    tags: ['saas', 'b2b', 'enterprise'],
    industry: 'Technology',
    jobTitle: 'VP of Marketing',
    healthScore: 88,
    engagementScore: 92,
    lastContactedAt: '2026-04-05T10:30:00Z',
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-04-05T10:30:00Z',
    isClient: false,
    contractValue: 24000,
    ltv: 72000,
    notes: 'Very interested in the enterprise plan. Needs approval from CFO.',
    interactions: [
      {
        id: 'i1',
        contactId: 'c1',
        type: 'email_sent',
        direction: 'outbound',
        subject: 'Enterprise Plan Proposal',
        sentAt: '2026-04-05T10:30:00Z',
        opened: true,
        clicked: true,
        replied: false,
      },
      {
        id: 'i2',
        contactId: 'c1',
        type: 'call',
        direction: 'outbound',
        subject: 'Discovery call — 45 min',
        sentAt: '2026-04-03T14:00:00Z',
      },
    ],
  },
  {
    id: 'c2',
    name: 'James Okafor',
    email: 'james@brightlabs.dev',
    company: 'BrightLabs',
    phone: '+1 (650) 555-0202',
    source: 'website',
    stage: 'engaged',
    tags: ['startup', 'dev-tools'],
    industry: 'Software',
    jobTitle: 'CTO',
    healthScore: 74,
    engagementScore: 78,
    lastContactedAt: '2026-04-04T09:15:00Z',
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-04-04T09:15:00Z',
    isClient: false,
    contractValue: 12000,
    ltv: 36000,
    interactions: [
      {
        id: 'i3',
        contactId: 'c2',
        type: 'email_received',
        direction: 'inbound',
        subject: 'Re: Integration questions',
        sentAt: '2026-04-04T09:15:00Z',
        opened: true,
        replied: true,
      },
      {
        id: 'i4',
        contactId: 'c2',
        type: 'linkedin_message',
        direction: 'outbound',
        subject: 'LinkedIn intro message',
        sentAt: '2026-03-28T11:00:00Z',
      },
    ],
  },
  {
    id: 'c3',
    name: 'Priya Sharma',
    email: 'priya.sharma@nexushealth.com',
    company: 'NexusHealth',
    source: 'cold',
    stage: 'nurturing',
    tags: ['healthcare', 'mid-market'],
    industry: 'Healthcare',
    jobTitle: 'Director of Operations',
    healthScore: 61,
    engagementScore: 55,
    lastContactedAt: '2026-03-28T16:00:00Z',
    createdAt: '2026-02-20T08:00:00Z',
    updatedAt: '2026-03-28T16:00:00Z',
    isClient: false,
    ltv: 18000,
    interactions: [
      {
        id: 'i5',
        contactId: 'c3',
        type: 'email_sent',
        direction: 'outbound',
        subject: 'Healthcare compliance white paper',
        sentAt: '2026-03-28T16:00:00Z',
        opened: true,
        clicked: false,
        replied: false,
      },
    ],
  },
  {
    id: 'c4',
    name: 'Marcus Webb',
    email: 'marcus.webb@pinnacle.co',
    company: 'Pinnacle Consulting',
    source: 'warm',
    stage: 'contacted',
    tags: ['consulting', 'smb'],
    industry: 'Consulting',
    jobTitle: 'Managing Partner',
    healthScore: 45,
    engagementScore: 40,
    lastContactedAt: '2026-03-20T10:00:00Z',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-03-20T10:00:00Z',
    isClient: false,
    ltv: 9600,
    interactions: [
      {
        id: 'i6',
        contactId: 'c4',
        type: 'email_sent',
        direction: 'outbound',
        subject: 'Introduction to our services',
        sentAt: '2026-03-20T10:00:00Z',
        opened: false,
        clicked: false,
        replied: false,
      },
    ],
  },
  {
    id: 'c5',
    name: 'Elena Torres',
    email: 'elena@cloudvault.ai',
    company: 'CloudVault AI',
    source: 'inbound',
    stage: 'client',
    tags: ['ai', 'enterprise', 'saas'],
    industry: 'Artificial Intelligence',
    jobTitle: 'CEO',
    healthScore: 95,
    engagementScore: 97,
    lastContactedAt: '2026-04-06T08:00:00Z',
    createdAt: '2025-10-01T08:00:00Z',
    updatedAt: '2026-04-06T08:00:00Z',
    isClient: true,
    contractValue: 48000,
    ltv: 144000,
    interactions: [
      {
        id: 'i7',
        contactId: 'c5',
        type: 'meeting',
        direction: 'inbound',
        subject: 'Quarterly business review',
        sentAt: '2026-04-06T08:00:00Z',
      },
      {
        id: 'i8',
        contactId: 'c5',
        type: 'note',
        direction: 'outbound',
        subject: 'Wants to expand to 3 new departments in Q3',
        sentAt: '2026-04-01T12:00:00Z',
      },
    ],
  },
  {
    id: 'c6',
    name: 'Derek Huang',
    email: 'derek.huang@finserv.com',
    company: 'FinServ Corp',
    source: 'referral',
    stage: 'new_lead',
    tags: ['fintech', 'enterprise'],
    industry: 'Finance',
    jobTitle: 'Head of Digital Transformation',
    healthScore: 30,
    engagementScore: 25,
    lastContactedAt: '2026-04-07T07:00:00Z',
    createdAt: '2026-04-07T07:00:00Z',
    updatedAt: '2026-04-07T07:00:00Z',
    isClient: false,
    ltv: 0,
    interactions: [
      {
        id: 'i9',
        contactId: 'c6',
        type: 'stage_change',
        direction: 'outbound',
        subject: 'Moved to New Lead',
        sentAt: '2026-04-07T07:00:00Z',
      },
    ],
  },
  {
    id: 'c7',
    name: 'Nadia Kovalev',
    email: 'nadia@retentionpro.io',
    company: 'RetentionPro',
    source: 'website',
    stage: 'retained',
    tags: ['saas', 'retention', 'enterprise'],
    industry: 'Technology',
    jobTitle: 'Chief Customer Officer',
    healthScore: 82,
    engagementScore: 85,
    lastContactedAt: '2026-04-02T14:00:00Z',
    createdAt: '2025-06-15T08:00:00Z',
    updatedAt: '2026-04-02T14:00:00Z',
    isClient: true,
    contractValue: 36000,
    ltv: 108000,
    interactions: [
      {
        id: 'i10',
        contactId: 'c7',
        type: 'email_received',
        direction: 'inbound',
        subject: 'Renewal confirmation for 2026',
        sentAt: '2026-04-02T14:00:00Z',
        opened: true,
        replied: true,
      },
    ],
  },
  {
    id: 'c8',
    name: 'Tobias Renn',
    email: 'tobias@blueridge-mfg.de',
    company: 'BlueRidge Manufacturing',
    source: 'cold',
    stage: 'engaged',
    tags: ['manufacturing', 'mid-market'],
    industry: 'Manufacturing',
    jobTitle: 'Operations Director',
    healthScore: 67,
    engagementScore: 60,
    lastContactedAt: '2026-04-01T11:00:00Z',
    createdAt: '2026-03-05T08:00:00Z',
    updatedAt: '2026-04-01T11:00:00Z',
    isClient: false,
    ltv: 28000,
    interactions: [
      {
        id: 'i11',
        contactId: 'c8',
        type: 'sms',
        direction: 'outbound',
        subject: 'Following up on demo request',
        sentAt: '2026-04-01T11:00:00Z',
      },
    ],
  },
];

export const sequences: Sequence[] = [
  {
    id: 'seq1',
    name: 'Cold Outreach — SaaS Decision Makers',
    description: 'A 5-step cold outreach sequence targeting SaaS VP/C-suite.',
    type: 'cold_outreach',
    status: 'active',
    steps: [
      {
        id: 'step1',
        sequenceId: 'seq1',
        order: 1,
        type: 'email',
        subject: 'Quick question about [Company]',
        body: 'Hi {{firstName}}, ...',
        delayDays: 0,
        delayHours: 0,
      },
      {
        id: 'step2',
        sequenceId: 'seq1',
        order: 2,
        type: 'linkedin',
        body: 'Connection request + note',
        delayDays: 2,
        delayHours: 0,
      },
      {
        id: 'step3',
        sequenceId: 'seq1',
        order: 3,
        type: 'email',
        subject: 'One more thought...',
        body: 'Hi {{firstName}}, following up...',
        delayDays: 3,
        delayHours: 0,
      },
    ],
    stats: { enrolled: 48, completed: 12, replied: 9, converted: 3 },
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-03-15T08:00:00Z',
  },
  {
    id: 'seq2',
    name: 'Warm Nurture — Inbound Leads',
    description: 'Nurture warm inbound leads through value-add content.',
    type: 'warm_nurture',
    status: 'active',
    steps: [
      {
        id: 'step4',
        sequenceId: 'seq2',
        order: 1,
        type: 'email',
        subject: 'Welcome + getting started guide',
        body: 'Hi {{firstName}}, thanks for reaching out...',
        delayDays: 0,
        delayHours: 0,
      },
      {
        id: 'step5',
        sequenceId: 'seq2',
        order: 2,
        type: 'email',
        subject: '3 ways companies like yours use [Product]',
        body: 'Hi {{firstName}}, here are some examples...',
        delayDays: 4,
        delayHours: 0,
      },
    ],
    stats: { enrolled: 31, completed: 18, replied: 14, converted: 7 },
    createdAt: '2026-01-20T08:00:00Z',
    updatedAt: '2026-03-20T08:00:00Z',
  },
  {
    id: 'seq3',
    name: 'Client Onboarding Flow',
    description: 'Structured onboarding for new clients over 30 days.',
    type: 'client_onboarding',
    status: 'active',
    steps: [
      {
        id: 'step6',
        sequenceId: 'seq3',
        order: 1,
        type: 'email',
        subject: 'Welcome to [Product] — your onboarding checklist',
        body: 'Hi {{firstName}}, welcome aboard!...',
        delayDays: 0,
        delayHours: 0,
      },
    ],
    stats: { enrolled: 12, completed: 8, replied: 10, converted: 8 },
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-03-01T08:00:00Z',
  },
  {
    id: 'seq4',
    name: 'Re-engagement Campaign',
    description: 'Win back cold contacts who went dark after initial outreach.',
    type: 'warm_nurture',
    status: 'paused',
    steps: [
      {
        id: 'step7',
        sequenceId: 'seq4',
        order: 1,
        type: 'email',
        subject: 'Still relevant for you?',
        body: 'Hi {{firstName}}, it has been a while...',
        delayDays: 0,
        delayHours: 0,
      },
    ],
    stats: { enrolled: 22, completed: 5, replied: 3, converted: 1 },
    createdAt: '2026-02-10T08:00:00Z',
    updatedAt: '2026-03-10T08:00:00Z',
  },
  {
    id: 'seq5',
    name: 'Upsell — Premium Tier',
    description: 'Targeted upsell sequence for existing clients on basic tier.',
    type: 'upsell',
    status: 'active',
    steps: [
      {
        id: 'step8',
        sequenceId: 'seq5',
        order: 1,
        type: 'email',
        subject: 'You are outgrowing your current plan',
        body: 'Hi {{firstName}}, based on your usage...',
        delayDays: 0,
        delayHours: 0,
      },
    ],
    stats: { enrolled: 15, completed: 6, replied: 5, converted: 4 },
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-04-01T08:00:00Z',
  },
];

export const campaigns: Campaign[] = [
  {
    id: 'camp1',
    name: 'Q1 SaaS Cold Outreach',
    type: 'sequence',
    status: 'completed',
    sequenceId: 'seq1',
    audienceCount: 150,
    openRate: 42.3,
    clickRate: 18.7,
    replyRate: 11.2,
    conversionRate: 4.1,
    startDate: '2026-01-15T00:00:00Z',
    endDate: '2026-03-31T00:00:00Z',
    abVariants: [
      {
        id: 'ab1',
        name: 'Variant A — Pain Point Lead',
        subject: 'Quick question about [Company]',
        body: 'Hi {{firstName}}, I noticed...',
        openRate: 44.1,
        clickRate: 19.2,
        replyRate: 12.0,
        audience: 75,
      },
      {
        id: 'ab2',
        name: 'Variant B — Curiosity Lead',
        subject: 'Interesting finding about [Industry]',
        body: 'Hi {{firstName}}, I came across...',
        openRate: 40.5,
        clickRate: 18.2,
        replyRate: 10.4,
        audience: 75,
      },
    ],
  },
  {
    id: 'camp2',
    name: 'April Warm Nurture Blast',
    type: 'email',
    status: 'active',
    audienceCount: 86,
    openRate: 55.4,
    clickRate: 27.1,
    replyRate: 15.6,
    conversionRate: 8.2,
    startDate: '2026-04-01T00:00:00Z',
    abVariants: [],
  },
];

export const insights: AIInsight[] = [
  {
    id: 'ins1',
    contactId: 'c1',
    type: 'ready_to_buy',
    confidence: 91,
    recommendation:
      'Sarah has opened your last 4 emails and clicked the pricing page twice. Send a direct call-to-action with a time-limited offer to close this week.',
    createdAt: '2026-04-06T06:00:00Z',
    signalStrength: 9,
  },
  {
    id: 'ins2',
    contactId: 'c4',
    type: 'churn_risk',
    confidence: 78,
    recommendation:
      'Marcus has not opened any email in 18 days and engagement has dropped significantly. Consider a personal video message or phone call to re-establish contact.',
    createdAt: '2026-04-05T06:00:00Z',
    signalStrength: 7,
  },
  {
    id: 'ins3',
    contactId: 'c5',
    type: 'upsell_opportunity',
    confidence: 85,
    recommendation:
      'Elena and her team have hit usage limits for 3 consecutive months. Propose the Enterprise tier with a custom SLA — projected +$24K ARR.',
    createdAt: '2026-04-04T06:00:00Z',
    signalStrength: 8,
  },
  {
    id: 'ins4',
    contactId: 'c3',
    type: 'cold_reengagement',
    confidence: 72,
    recommendation:
      'Priya opened your white paper but has not replied in 10 days. A personalised follow-up referencing the white paper content may reignite the conversation.',
    createdAt: '2026-04-03T06:00:00Z',
    signalStrength: 6,
  },
  {
    id: 'ins5',
    contactId: 'c7',
    type: 'upsell_opportunity',
    confidence: 80,
    recommendation:
      'Nadia has renewed and her NPS score is 9. She is an ideal candidate for a referral programme or expansion into adjacent business units.',
    createdAt: '2026-04-02T06:00:00Z',
    signalStrength: 8,
  },
];
